version: '3.8'

services:
  backend:
    image: rapidsai/notebooks:25.06a-cuda12.8-py3.12
    pull_policy: always
    ulimits:
      memlock: -1
      stack: 67108864
    shm_size: 1g
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    environment:
        EXTRA_PIP_PACKAGES: "anndata==0.11.4 array-api-compat==1.12.0 contourpy==1.3.2 cycler==0.12.1 fonttools==4.58.0 h5py==3.13.0 imageio==2.37.0 joblib==1.5.1 kiwisolver==1.4.8 lazy-loader==0.4 legacy-api-wrap==1.4.1 llvmlite==0.44.0 matplotlib==3.10.3 natsort==8.4.0 networkx==3.4.2 numba==0.61.2 numpy==2.2.6 pandas==2.2.3 patsy==1.0.1 pillow==11.2.1 pynndescent==0.5.13 rapids-singlecell==0.12.6 scanpy==1.11.1 scikit-learn==1.5.2 scikit-image==0.25.2 scikit-misc==0.5.1 scipy==1.15.3 seaborn==0.13.2 session-info2==0.1.2 statsmodels==0.14.4 threadpoolctl==3.6.0 tifffile==2025.5.10 tqdm==4.67.1 tzdata==2025.2 umap-learn==0.5.7 wget==3.2 deprecated==1.2.18 numcodecs==0.15.1 wrapt==1.17.2 zarr==2.18.7"
    ports:
      - "0.0.0.0:8888:8888"      # JupyterLab
      - "0.0.0.0:8787:8787"      # Dask dashboard
      - "0.0.0.0:8786:8786"      # Dask scheduler
    volumes:
      - /home/ubuntu/single-cell-analysis-blueprint:/notebooks/
      - /ephemeral:/notebooks/data
    user: root
    working_dir: /notebooks
    entrypoint: ["/home/rapids/entrypoint.sh"]
    command: python -m jupyter lab --allow-root --ip=0.0.0.0 --no-browser --NotebookApp.token='' --NotebookApp.password='' --notebook-dir=/notebooks
    restart: unless-stopped
